<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Commands\Expenso.Shared.Commands.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Database\Expenso.Shared.Database.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Queries.Pagination\Expenso.Shared.Queries.Pagination.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Queries\Expenso.Shared.Queries.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.System.Expressions\Expenso.Shared.System.Expressions.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.System.Modules.Constants\Expenso.Shared.System.Modules.Constants.csproj"/>
        <ProjectReference Include="..\Expenso.BudgetSharing.Domain\Expenso.BudgetSharing.Domain.csproj"/>
        <ProjectReference Include="..\Expenso.BudgetSharing.Shared\Expenso.BudgetSharing.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Expenso.BudgetSharing.Tests.ArchTests"/>
        <InternalsVisibleTo Include="Expenso.BudgetSharing.Tests.UnitTests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="BudgetPermissions\Write\DeleteBudgetPermission\DTO\"/>
        <Folder Include="BudgetPermissions\Write\RemovePermission\DTO\"/>
    </ItemGroup>

</Project>
