// <auto-generated />
using System;
using Expenso.UserPreferences.Core.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Expenso.UserPreferences.Core.Persistence.EfCore.Migrations
{
    [DbContext(typeof(UserPreferencesDbContext))]
    partial class UserPreferencesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("UserPreferences")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expenso.UserPreferences.Core.Domain.Preferences.Model.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Preferences", "UserPreferences");
                });

            modelBuilder.Entity("Expenso.UserPreferences.Core.Domain.Preferences.Model.Preference", b =>
                {
                    b.OwnsOne("Expenso.UserPreferences.Core.Domain.Preferences.Model.ValueObjects.FinancePreference", "FinancePreference", b1 =>
                        {
                            b1.Property<Guid>("PreferenceId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowAddFinancePlanReviewers")
                                .HasColumnType("boolean")
                                .HasColumnName("AllowAddFinancePlanReviewers");

                            b1.Property<bool>("AllowAddFinancePlanSubOwners")
                                .HasColumnType("boolean")
                                .HasColumnName("AllowAddFinancePlanSubOwners");

                            b1.Property<int>("MaxNumberOfFinancePlanReviewers")
                                .HasColumnType("integer")
                                .HasColumnName("MaxNumberOfFinancePlanReviewers");

                            b1.Property<int>("MaxNumberOfSubFinancePlanSubOwners")
                                .HasColumnType("integer")
                                .HasColumnName("MaxNumberOfSubFinancePlanSubOwners");

                            b1.HasKey("PreferenceId");

                            b1.ToTable("Preferences", "UserPreferences");

                            b1.WithOwner()
                                .HasForeignKey("PreferenceId");
                        });

                    b.OwnsOne("Expenso.UserPreferences.Core.Domain.Preferences.Model.ValueObjects.GeneralPreference", "GeneralPreference", b1 =>
                        {
                            b1.Property<Guid>("PreferenceId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("UseDarkMode")
                                .HasColumnType("boolean");

                            b1.HasKey("PreferenceId");

                            b1.ToTable("Preferences", "UserPreferences");

                            b1.WithOwner()
                                .HasForeignKey("PreferenceId");
                        });

                    b.OwnsOne("Expenso.UserPreferences.Core.Domain.Preferences.Model.ValueObjects.NotificationPreference", "NotificationPreference", b1 =>
                        {
                            b1.Property<Guid>("PreferenceId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("SendFinanceReportEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("SendFinanceReportEnabled");

                            b1.Property<int>("SendFinanceReportInterval")
                                .HasColumnType("integer")
                                .HasColumnName("SendFinanceReportInterval");

                            b1.HasKey("PreferenceId");

                            b1.ToTable("Preferences", "UserPreferences");

                            b1.WithOwner()
                                .HasForeignKey("PreferenceId");
                        });

                    b.Navigation("FinancePreference");

                    b.Navigation("GeneralPreference");

                    b.Navigation("NotificationPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
