### GetUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/f68546d6-fc1b-48cb-93d8-b96b29d8666d?
    includeFinancePreferences=true&includeNotificationPreferences=true&includeGeneralPreferences=true
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetCurrentUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/current-user?includeFinancePreferences=true&
    includeNotificationPreferences=true&includeGeneralPreferences=true
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences?
    userId=4c7a9020-398f-4d42-8cb4-cac1477a49ac&includeFinancePreferences=true&includeNotificationPreferences=true&
    includeGeneralPreferences=true
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### CreatePreferences 
POST {{apiHostAddress}}/{{userPreferencesRoute}}/preferences
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "userId": "4c7a9020-398f-4d42-8cb4-cac1477a49ac"
}

### UpdatePreferences
PUT {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/f68546d6-fc1b-48cb-93d8-b96b29d8666d
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "FinancePreference": {
    "allowAddFinancePlanSubOwners": true,
    "maxNumberOfSubFinancePlanSubOwners": 5,
    "allowAddFinancePlanReviewers": true,
    "maxNumberOfFinancePlanReviewers": 10
  },
  "NotificationPreference": {
    "sendFinanceReportEnabled": true,
    "sendFinanceReportInterval": 5
  },
  "GeneralPreference": {
    "useDarkMode": true
  }
}
