### GetPreference
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/0d002552-918f-4a1f-b114-7b4138147148?
    preferenceType=Finance,Notification,General
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetCurrentUserPreference
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/current-user?preferenceType=Finance,Notification,General
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences?PreferenceId=0d002552-918f-4a1f-b114-7b4138147148&
    preferenceType=Finance,Notification,General
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### CreatePreference
POST {{apiHostAddress}}/{{userPreferencesRoute}}/preferences
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "userId": "4c7a9020-398f-4d42-8cb4-cac1477a49ac"
}

### UpdatePreference
PUT {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/0d002552-918f-4a1f-b114-7b4138147148
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "FinancePreference": {
    "allowAddFinancePlanSubOwners": true,
    "maxNumberOfSubFinancePlanSubOwners": 5,
    "allowAddFinancePlanReviewers": true,
    "maxNumberOfFinancePlanReviewers": 10
  },
  "NotificationPreference": {
    "sendFinanceReportEnabled": true,
    "sendFinanceReportInterval": 5
  },
  "GeneralPreference": {
    "useDarkMode": true
  }
}
