### GetPreference
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/f5f4e46d-4ec0-4abb-a631-3aa9603a4448?
    includes=Finance,Notification,General
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetCurrentUserPreference
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/current-user?includes=Finance,Notification,General
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences?PreferenceId=f5f4e46d-4ec0-4abb-a631-3aa9603a4448&
    includes=Finance,Notification,General
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### CreatePreference
POST {{apiHostAddress}}/{{userPreferencesRoute}}/preferences
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "userId": "4c7a9020-398f-4d42-8cb4-cac1477a49ac"
}

### UpdatePreference
PUT {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/f5f4e46d-4ec0-4abb-a631-3aa9603a4448
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "FinancePreference": {
    "allowAddFinancePlanSubOwners": true,
    "maxNumberOfSubFinancePlanSubOwners": 5,
    "allowAddFinancePlanReviewers": true,
    "maxNumberOfFinancePlanReviewers": 10
  },
  "NotificationPreference": {
    "sendFinanceReportEnabled": true,
    "sendFinanceReportInterval": 5
  },
  "GeneralPreference": {
    "useDarkMode": true
  }
}
