version = 1

exclude_patterns = [
    ".husky/**",
    ".github/**",
    ".docker/**",
    ".scripts/**",
    "Tests/**",
]

test_patterns = [
    "Tests/**"
]

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true