version = 1

exclude_patterns = [
    ".husky/**",
    ".github/**",
    ".docker/**",
    ".scripts/**"
]

test_patterns = [
    "Tests/**",
    "**/Tests/**",
    "**/**/Tests/**"
    "**/**/**/Tests/**"
]

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true