version = 1

exclude_patterns = [
    ".husky/**",
    ".github/**",
    ".docker/**",
    ".scripts/**"
]

test_patterns = [
    "Tests/**",
    "Src/Commands/Tests/**",
    "Src/Core/Tests/**",
    "Src/Domain/Tests/**",
    "Src/Queries/Tests/**",
    "*Tests.cs"
]

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true