### GetBudgetPermissionRequest
GET {{apiHostAddress}}/{{budgetSharingRoute}}/budget-permission-requests/118c69a3-379b-45d0-ba83-9e5610083c06
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetBudgetPermissionRequests
GET {{apiHostAddress}}/{{budgetSharingRoute}}/budget-permission-requests?status=1&
    budgetId=fab3cf10-e0da-4bcb-b41c-dfbba1382215
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### AssignParticipant
POST {{apiHostAddress}}/{{budgetSharingRoute}}/budget-permission-requests
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "BudgetId": "fab3cf10-e0da-4bcb-b41c-dfbba1382215",
  "Email": "admin@email.com",
  "PermissionType": 2,
  "ExpirationDays": 3
}

### ConfirmAssigningParticipant
PATCH {{apiHostAddress}}/{{budgetSharingRoute}}/budget-permission-requests/118c69a3-379b-45d0-ba83-9e5610083c06/confirm
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### ExpireAssigningParticipant
PATCH {{apiHostAddress}}/{{budgetSharingRoute}}/budget-permission-requests/118c69a3-379b-45d0-ba83-9e5610083c06/expire
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### CancelAssigningParticipant
PATCH {{apiHostAddress}}/{{budgetSharingRoute}}/budget-permission-requests/118c69a3-379b-45d0-ba83-9e5610083c06/cancel
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}