### Hello
GET {{apiHostAddress}}/{{greetingsRoute}}/hello
Content-Type: application/json

### HelloUser
GET {{apiHostAddress}}/{{greetingsRoute}}/hello-user
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}