namespace Expenso.UserPreferences.Core.Application.Preferences.DTO.CreatePreference.Response;

public sealed record CreateNotificationPreferenceResponse(bool SendFinanceReportEnabled, int SendFinanceReportInterval);