<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Commands.Validation\Expenso.Shared.Commands.Validation.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Commands\Expenso.Shared.Commands.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.System.Logging\Expenso.Shared.System.Logging.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.System.Modules.Constants\Expenso.Shared.System.Modules.Constants.csproj"/>
        <ProjectReference Include="..\Expenso.Communication.Shared\Expenso.Communication.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Expenso.Communication.Tests.ArchTests"/>
        <InternalsVisibleTo Include="Expenso.Communication.Tests.UnitTests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6"/>
    </ItemGroup>

</Project>
