### Hello
GET {{apiHostAddress}}/{{greetingsRoute}}/hello
Accept: application/json

### HelloUser
GET {{apiHostAddress}}/{{greetingsRoute}}/hello-user
Accept: application/json
Authorization: Bearer {{accessToken}}