### GetUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/8b6f6926-7513-4791-a59a-8f0bba6fa216
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetCurrentUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/current-user
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences?userId=4c7a9020-398f-4d42-8cb4-cac1477a49ac
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### CreatePreferences
POST {{apiHostAddress}}/{{userPreferencesRoute}}/preferences
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "userId": "4c7a9020-398f-4d42-8cb4-cac1477a49ac"
}

### UpdatePreferences
PUT {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/4c7a9020-398f-4d42-8cb4-cac1477a49ac
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "FinancePreference": {
    "allowAddFinancePlanSubOwners": true,
    "maxNumberOfSubFinancePlanSubOwners": 5,
    "allowAddFinancePlanReviewers": true,
    "maxNumberOfFinancePlanReviewers": 10
  },
  "NotificationPreference": {
    "sendFinanceReportEnabled": true,
    "sendFinanceReportInterval": 5
  },
  "GeneralPreference": {
    "useDarkMode": true
  }
}
