### GetUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/a433bf38-4ece-4d43-b4a1-b46cf9f4cae5
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetCurrentUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/current-user
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetUserPreferences
GET {{apiHostAddress}}/{{userPreferencesRoute}}/preferences?userId=e2bf7ed6-afce-4c25-a5c3-66b3e7cfe006
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### CreatePreferences
POST {{apiHostAddress}}/{{userPreferencesRoute}}/preferences
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "userId": "e2bf7ed6-afce-4c25-a5c3-66b3e7cfe006"
}

### UpdatePreferences
PUT {{apiHostAddress}}/{{userPreferencesRoute}}/preferences/a433bf38-4ece-4d43-b4a1-b46cf9f4cae5
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "FinancePreference": {
    "allowAddFinancePlanSubOwners": true,
    "maxNumberOfSubFinancePlanSubOwners": 5,
    "allowAddFinancePlanReviewers": true,
    "maxNumberOfFinancePlanReviewers": 10
  },
  "NotificationPreference": {
    "sendFinanceReportEnabled": true,
    "sendFinanceReportInterval": 5
  },
  "GeneralPreference": {
    "useDarkMode": true
  }
}