namespace Expenso.UserPreferences.Core.Application.Preferences.Write.Commands.CreatePreference.Internal.DTO.Response;

public sealed record CreateNotificationPreferenceResponse(bool SendFinanceReportEnabled, int SendFinanceReportInterval);