<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Expenso.BudgetSharing.Tests.ArchTests"/>
        <InternalsVisibleTo Include="Expenso.BudgetSharing.Tests.UnitTests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.5"/>
        <PackageReference Include="Scrutor" Version="6.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Integration.Events\Expenso.Shared.Integration.Events.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="DTO\API\BudgetPermissionRequests\AssignParticipant\"/>
        <Folder Include="DTO\API\BudgetPermissions\DeleteBudgetPermission\"/>
    </ItemGroup>

</Project>
