<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IdentityModel" Version="7.0.0"/>
        <PackageReference Include="Keycloak.AuthServices.Sdk" Version="2.6.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.7"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Queries.Pagination\Expenso.Shared.Queries.Pagination.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.System.Configuration\Expenso.Shared.System.Configuration.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.Queries\Expenso.Shared.Queries.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.System.Modules.Constants\Expenso.Shared.System.Modules.Constants.csproj"/>
        <ProjectReference Include="..\..\Shared\Expenso.Shared.System.Types\Expenso.Shared.System.Types.csproj"/>
        <ProjectReference Include="..\Expenso.IAM.Shared\Expenso.IAM.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Expenso.IAM.Tests.ArchTests"/>
        <InternalsVisibleTo Include="Expenso.IAM.Tests.UnitTests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

</Project>
