namespace Expenso.BudgetSharing.Shared.DTO.MessageBus.BudgetPermissionRequests.ExpireAssigningParticipant.Payload;

public sealed record BudgetPermissionRequestExpiredPayload(Guid BudgetPermissionRequestId);