### GetJob
GET {{apiHostAddress}}/{{timeManagementRoute}}/job-entries/02bbed61-600f-4725-a166-b884cc7c8ff2
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### GetJobs
GET {{apiHostAddress}}/{{timeManagementRoute}}/job-entries?isActive=false&includes=3
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

### RegisterJob
POST {{apiHostAddress}}/{{timeManagementRoute}}/job-entries
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "maxRetries": 5,
  "jobEntryTriggers": [
    {
      "eventType": "BudgetPermissionRequestExpired",
      "eventData": "{\"MessageContext\":{\"ModuleId\":\"BudgetSharingModule\",\"MessageId\":\"27c03f96-6434-49d9-8505-220d9b8787c2\",\"CorrelationId\":\"afc02050-4f31-4e12-8fc2-a5f496208402\",\"RequestedBy\":\"b07b57fd-ebaf-482e-a008-8ffa48df56c0\",\"Timestamp\":\"2024-09-06T17:05:06.0879277+02:00\"},\"BudgetPermissionRequestId\":\"27a6199c-cdea-43fe-b5f3-a4c4bc6ae551\"}"
    }
  ],
  "interval": {
    "minute": 15
  }
}

### CancelJob
DELETE {{apiHostAddress}}/{{timeManagementRoute}}/job-entries/98600381-7e59-4cde-bc97-c20daca4d071
Content-Type: application/json
Authorization: Bearer {{apiAccessToken}}

{
  "jobEntryId": "95c37bc4-b43d-4653-8dca-718dedf37cbe"
}
