name: audit
on:
  schedule:
    - cron: "0 10 * * *"
env:
  DOTNET_VERSION: "8.0.x"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  code-ql:
    uses: ./.github/workflows/code-ql.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  trivy:
    uses: ./.github/workflows/trivy.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
