name: Security audit - CodeQL
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
env:
  DOTNET_VERSION: "8.0.0-rc.2"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

  initialize-codeql:
    name: Initialize CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v2
        with:
          languages: "csharp"

  setup-dotnet:
    name: Setup .NET
    runs-on: ubuntu-latest
    needs: initialize-codeql
    strategy:
      matrix:
        dotnet-version: [ "8.0.0-rc.2" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/piotrkantorowicz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.ACTION_GITHUB_TOKEN}}

  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: setup-dotnet
    steps:
      - uses: actions/checkout@v4
      - run: dotnet restore

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - run: dotnet build

  perform-codeql:
    name: Perform CodeQL Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/analyze@v2
