name: Build and test on pull request
on:
  pull_request:
    branches: [ main ]
env:
  DOTNET_VERSION: "8.0.x"

jobs:
  setup-dotnet:
    name: Setup .NET
    strategy:
      matrix:
        dotnet-version: [ "8.0.x" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/piotrkantorowicz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.ACTION_GITHUB_TOKEN}}

  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: setup-dotnet
    steps:
      - uses: actions/checkout@v4
      - run: dotnet restore

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - run: dotnet build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: dotnet test --no-build --settings tests.runsettings --results-directory "TestResults" --collect:"XPlat Code Coverage"

  upload-coverage-reports-to-codecov:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  upload-test-results:
    name: Upload test results
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults

  upload-report:
    name: Tests report generation
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: test-results (${{ env.DOTNET_VERSION }})
          path: "TestResults/*.trx"
          reporter: dotnet-trx
          list-tests: "failed"
