name: deploy
on:
  push:
    branches: [main]

permissions:
  actions: read
  packages: write
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  code-ql:
    uses: ./.github/workflows/reusable-code-ql.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  trivy:
    uses: ./.github/workflows/reusable-trivy.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  test:
    uses: ./.github/workflows/reusable-test.yml
    needs: [trivy, code-ql]
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  buid-and-push-docker-image-to-ghcr:
    needs: test
    uses: ./.github/workflows/reusable-build&push_docker_image.yml
    with:
      registry: ghcr.io
      image: ghcr.io/${{ github.actor }}/expenso
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}
