name: pull-request
on:
  pull_request:
    branches: [ main, dev ]
    types: [ opened, synchronize, reopened ]

permissions:
  actions: read
  packages: write
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  sanity:
    uses: ./.github/workflows/reusable-sanity.yml

  check_changes:
    uses: ./.github/workflows/reusable-check-changes.yml
    with:
      path: 'Src/**'
    needs: sanity

  code-ql:
    uses: ./.github/workflows/reusable-code-ql.yml
    needs: check_changes

  trivy:
    uses: ./.github/workflows/reusable-trivy.yml
    needs: check_changes

  test:
    uses: ./.github/workflows/reusable-test.yml
    if: needs.check_changes.outputs.changed == 'true'
    needs: [ trivy, code-ql ]
