name: pull-request
on:
  pull_request:
    branches: [ main, dev ]
    types: [ opened, synchronize, reopened ]

permissions:
  actions: read
  packages: write
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  sanity:
    uses: ./.github/workflows/reusable-sanity.yml

  code-ql:
    uses: ./.github/workflows/reusable-code-ql.yml
    needs: sanity

  trivy:
    uses: ./.github/workflows/reusable-trivy.yml
    needs: sanity

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      src_changed: ${{ steps.check_changes.outputs.src_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for API changes
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^Src/'
          then
            echo "::set-output name=src_changed::true"
          else
            echo "::set-output name=src_changed::false"
          fi
    needs: [ trivy, code-ql ]

  test:
    uses: ./.github/workflows/reusable-test.yml
    if: needs.check_changes.outputs.src_changed == 'true'
    needs: check_changes
