name: test
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_call:
env:
  DOTNET_VERSION: "8.0.x"

permissions:
  actions: read
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  sanity:
    uses: ./.github/workflows/reusable_sanity.yml

  code-ql:
    uses: ./.github/workflows/reusable_code-ql.yml
    needs: sanity
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  trivy:
    uses: ./.github/workflows/reusable_trivy.yml
    needs: sanity
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  test:
    uses: ./.github/workflows/reusable_test.yml
    needs: [ trivy, code-ql ]
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  bump-version:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: Bump version
        id: bump
        uses: ./.github/workflows/reusable_bump_version.yml
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  print-tag:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Print new tag
        run: echo "The new tag is ${{ needs.bump-version.outputs.new_tag }}"

  buid-push-docker-image:
    needs: bump-version
    uses: ./.github/workflows/reusable_build&push_docker_image.yml
    with:
      new_tag: ${{ needs.bump-version.outputs.new_tag }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
      docker_hub_token: ${{ secrets.DOCKER_PASSWORD }}
