name: test
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_call:
env:
  DOTNET_VERSION: "8.0.x"

permissions:
  actions: read
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  # sanity:
  #   uses: ./.github/workflows/reusable_sanity.yml

  # code-ql:
  #   uses: ./.github/workflows/reusable_code-ql.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}
  #   needs: sanity

  # trivy:
  #   uses: ./.github/workflows/reusable_trivy.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}
  #   needs: sanity

  # test:
  #   uses: ./.github/workflows/reusable_test.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}
  #   needs: [trivy, code-ql]

  # bump-version:
  #   uses: ./.github/workflows/reusable_bump-version.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}
  # needs: test

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0
      - name: bump version
        id: bump_version
        uses: ./.github/workflows/reusable_bump-version.yml
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print new tag
        run: echo "The new tag is ${{ steps.bump_version.outputs.new_tag }}"
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}

  another-job:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Use new tag
        run: echo "The new tag is ${{ needs.bump-version.outputs.new_tag }}"

  # buid-push-docker-image:
  #   uses: ./.github/workflows/reusable_build&push_docker_image.yml
  #   with:
  #     new_tag: ${{ needs.bump-version.outputs.new_tag }}
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}
  #     docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
  #     docker_hub_token: ${{ secrets.DOCKER_PASSWORD }}
  #   needs: bump-version
