name: test
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_call:
env:
  DOTNET_VERSION: "8.0.x"

permissions:
  contents: read
  actions: read
  id-token: write
  checks: write
  security-events: write

jobs:
  sanity:
    uses: ./.github/workflows/sanity/sanity.yml

  code-ql:
    uses: ./.github/workflows/security/code-ql.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  trivy:
    uses: ./.github/workflows/security/trivy.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  test:
    uses: ./.github/workflows/app/test.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
