name: bump-version
on:
  workflow_call:
    secrets:
      token:
        description: "The GitHub token to use for authentication"
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.token }}
          commit_sha: ${{ github.sha }}

      - name: Print new tag
        run: echo "The new tag is ${{ steps.tag_version.outputs.new_tag }}"

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
