name: check-changes
on:
  workflow_call:
    inputs:
      path:
        description: 'Path to check for changes'
        type: string
        default: 'Src/**'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter_changes.outputs.changed }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Check for source changes
        id: filter_changes
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            changed:
              - ${{ inputs.path }}
      - name: Print changed value
        run: echo ${{ steps.filter_changes.outputs.changed }}