name: bump-version
on:
  workflow_call:
    secrets:
      token:
        description: "The GitHub token to use for authentication"
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      # app_version: ${{ steps.semantic.outputs.version }}
      app_version: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0

      # - name: Semantic version
      #   uses: paulhatch/semantic-version@v5.3.0
      #   id: semantic

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ github.sha }}

      # - name: Tag commit
      #   uses: pkgdeps/git-tag-action@v2.0.6
      #   with:
      #     version: ${{ steps.semantic.outputs.version }}
      #     github_token: ${{ secrets.token }}
      #     github_repo: ${{ github.repository }}
      #     git_commit_sha: ${{ github.sha }}
      #     git_tag_prefix: "v"
